export const reducerCases = {
    SET_USER :"SET_USER",
    SET_TOKEN : "SET_TOKEN",
    SET_PLAYLISTS : "SET_PLAYLISTS",
    SET_PLAYING : "SET_PLAYING",
    SET_PLAYER_STATE : "SET_PLAYER_STATE",
    SET_USER_INFO : "SET_USER_INFO",
    SET_PLAYLIST : "SET_PLAYLIST",
    SET_PLAYLIST_ID : "SET_PLAYLIST_ID",
    SET_CURRENTPLAYING : "SET_CURRENTPLAYING",
}